### ISSUE TITLE
Add README / documentation for executing archive status update script and upgrade dd command

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-loader#14]
## 💡 Description

Per https://github.com/NASA-PDS/registry-loader/pull/13 and https://github.com/NASA-PDS/registry-mgr/pull/47, need some simple doc for how and when to run this. Probably a README alongside the registry-loader script, and an update to the registry-mgr documentation.

**Comment by jordanpadams** [comment]
@jimmie per our discussions about running the tool, can we just add a quick blurb to the Registry and/or Registry Loader README(s). Once off script, but worth tracking how we did it and why the script exists.

**Comment by jimmie** [comment]
Done.
