### ISSUE TITLE
Stable Roundup can no longer trigger Imaging workflow

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/registry-loader#26]
## 🐛 Describe the bug

After pushing a tag like `release/x.y.z`, the Roundup Action performs a release and then deletes the `release/x.y.z` tag. However, the Stable workflow then triggers the Imaging workflow via repository dispatch. The Imaging workflow then checks out `release/x.y.z`, but it no longer exists.

## 📜 To Reproduce

1. Push a tag like `release/x.y.z`
2. 🍿

## 🕵️ Expected behavior

Docker images are constructed and pushed to the Hub.

**Comment by tloubrieu-jpl** [comment]
+1

i am still having the error, see for example https://github.com/NASA-PDS/registry-loader/actions/runs/4577537624/jobs/8083064321

**Comment by tloubrieu-jpl** [comment]
I might be able to fix that

**Comment by tloubrieu-jpl** [comment]
I tried to add a `v` to the tag name generation in the workflow. I did not test. I will do my docker image manually for today and I am leaving this bug open.
