### ISSUE TITLE
README is just the template

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/registry-loader#7]
## 🐛 Describe the bug

The `README.md` for `registry-loader` is identical to the `pds-template-repo-java`'s `README.md`. It should be filled in with details specific to the `registry-loader` repository.

## 📜 To Reproduce

```console
$ git clone --quiet git@github.com:NASA-PDS/template-repo-java.git
$ git clone --quiet git@github.com:NASA-PDS/registry-loader.git
$ cmp template-repo-java/README.md registry-loader/README.md 
$ echo $?
0
```

## 🕵️ Expected behavior
```console
$ echo $?
1
```

##  🏞Screenshots

![Screen Shot 2022-03-21 at 7 54 37 AM](https://user-images.githubusercontent.com/814813/159265245-47534890-ed43-4761-b27e-6449c631f1b6.png)

## 🖥 System Info
 - OS: macOS 12.3
 - Browser: Safari 15.4 (17613.1.17.1.6)

---

**Comment by jordanpadams** [comment]
will be updated per #11
